### PR TITLE
Revision of FHE Part2

### PR DESCRIPTION
**Pull request by ZiangChen**
Dear Prof. Barak,

I revised some parts of the notes for FHE Part2. My teammate Yeongil will upload the CKKS part from his account. Do you have any suggestions? Many thanks!

Best regards,
Ziang Chen

### CODE REVIEW

**Comment by boazbk** [comment]
Thanks! Can you send a summary of the changes?

**Comment by ZiangChen** [comment]
Dear Prof. Barak,

Here's the summary of the changes:

1) Added some overviews, the definition of Noisy HE, and some arguments
about the depth of the circuit before section 17.1.

2) Fixed some minor errors and added a few explanations in Section
17.1-17.5.

3) Wrote Part 2 and 3 in Section 17.6, i.e., bandwidth-efficiency of FHE
and PIR.

My teammate Yeongil will upload Part 1 of Section 17.6 (CKKS) from his
account.

Many thanks!

Best regards,
Ziang

**Comment by ZiangChen** [comment]
Dear Prof. Barak,

Thanks a lot!
Parts in Section 17.6 seem to be in the wrong order. Maybe this is because
Yeongil and I upload different parts separately.

Best regards,
Ziang

**Comment by boazbk** [comment]
Can you make a pull request to fix this?

**Comment by ZiangChen** [comment]
Sure! We will do that.

Best,
Ziang

**Pull request merged**
